# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: name-tests-test
        stages: [commit]
      - id: requirements-txt-fixer
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: detect-aws-credentials
        stages: [commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        stages: [commit]
        args: [--py310-plus]
#  - repo: https://github.com/mgedmin/check-manifest
#    rev: "0.49"
#    hooks:
#      - id: check-manifest
#        stages: [commit]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.9
    hooks:
      - id: pymarkdown
        stages: [commit]
        pass_filenames: false
        args:
          - --config
          - pymarkdown_config.json
          - scan
          - .
          - ./docs
          - ./docs_sphinx
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        stages: [commit]



#  - repo: local
#    hooks:
#      - id: tests
#        name: run tests
#        entry: tox -e py36
#        language: system
#        types: [python]
#        stages: [push]
#        pass_filenames: false
#      - id: typing
#        name: run typing checks
#        entry: tox -e mypy
#        language: system
#        types: [python]
#        stages: [commit]
#        pass_filenames: false
#      - id: packaging
#        name: run checks on packaging
#        entry: tox -e packaging
#        language: system
#        types: [python]
#        stages: [push]
#        pass_filenames: false
#      - id: docs_sphinx
#        name: run checks on docs_sphinx building
#        entry: tox -e docs_sphinx
#        language: system
#        types: [python]
#        stages: [push]
#        pass_filenames: false
